# docker-compose.yml
version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/data/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
#  redis:
#    image: redis:alpine
#    ports:
#      - 6379:6379
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '81:80'
  php_web:
    build: docker/php7
    ports:
      - 9000:9000
    links:
      - db:mysqldb
    volumes:
      - "./:/var/www/app"
    environment:
      - "DATABASE_URL:mysql://root:@127.0.0.1:3306/pg_annuel"
      - "APP_ENV:prod"
      - "APP_SECRET:c948f2f28993826a697f61cacf4fcaad"
#  composer:
#      image: composer
#      volumes:
#        - "./:/app"
#      command: install --no-dev --optimize-autoloader
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    links:
      - php_web
    volumes_from:
      - php_web
    volumes:
      - "./docker/nginx/logs/:/var/log/nginx"
